# Generated by Django 4.0.5 on 2022-06-14 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_prestamo', models.DateField(auto_now_add=True)),
                ('fecha_devolucion', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(default='Pendiente', max_length=50)),
                ('usuario', models.CharField(default='Usuario', max_length=50)),
                ('libro', models.CharField(default='Libro', max_length=50)),
            ],
        ),
    ]
